version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "go_course"
    ports:
      - "3306:3306"
#    volumes:
#      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
